name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./app

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ${{env.working-directory}}
    - run: npm run production
      working-directory: ${{env.working-directory}}
      env:
        CI: true
    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: './app/dist'
        destination_dir: ''